CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_NICE_EPAPER_ON=y
CONFIG_NICE_OLED_ON=n
CONFIG_NICE_CUSTOM_ON=n

# Keep host-dependent features out of the default build.
CONFIG_NICE_OLED_WIDGET_RAW_HID=n
