name: Build Corne nice!view

on:
  push:
    paths:
      - ".github/workflows/build-corne-niceview.yml"
      - "boards/shields/nice_oled/**"
      - "ci/**"
      - "zephyr/module.yml"
  pull_request:
    paths:
      - ".github/workflows/build-corne-niceview.yml"
      - "boards/shields/nice_oled/**"
      - "ci/**"
      - "zephyr/module.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: ci/build.yaml
      config_path: ci-config
      archive_name: corne-nice-epaper
